#ifndef SRC__PLAY__TICTACTOE__AI_MACROS_H_INCLUDED
#define SRC__PLAY__TICTACTOE__AI_MACROS_H_INCLUDED

#define DEFAULT_POSITION_VALUE -2

#define MAIN_DIAGONAL_VALUE 1

#define SECONDARY_DIAGONAL_VALUE 0

#endif  // SRC__PLAY__TICTACTOE__AI_MACROS_H_INCLUDED