name: Bug report
description: Report a reproducible bug.

labels:
  - bug
assignees:
  - hozlucas28

title: "Bug: "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the template below as best as you can.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us, what did you expect to happen? and what actually happened?
      placeholder: I was trying to... and then...
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: In which environments did you experience this issue?
      description: Select the environments where you encountered the issue.
      options:
        - DevContainer
        - DevContainer (Docker Compose)
        - DevContainer (Docker Swarm)
        - Local machine
        - Local machine (Docker Compose)
        - Local machine (Docker Swarm)
      default: 0
      multiple: true
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce-it
    attributes:
      label: Steps to reproduce it
      description: Provide a step-by-step list of how to reproduce the issue.
      placeholder: |
        1. Send a request to...
        2. After that, do...
        3. Finally, see the issue on...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      placeholder: |
        2025-01-01 00:00:00 [error] Something bad happened!
      render: shell
