#ifndef SRC_MACROS_H_INCLUDED
#define SRC_MACROS_H_INCLUDED

#define DEVELOPMENT_TEAM "SQUASH"

#define DEVELOPMENT_TEAM_LENGTH 16

#define PLAYER_NAME_LENGTH 64

#define PLAYER_LAST_GAME_PLAYED_LENGTH 20

#endif  // SRC_MACROS_H_INCLUDED
